### ISSUE TITLE
programatically show marker's popup

### ISSUE THREAD

**Issue by bmeredyk** [soal/vue-mapbox#113]
What is the best way to programatically open the popup that is associated with a marker? I want users to be able to click on a location from a list outside the map and have the map zoom to that location and open its popup to show more information. I can get the map to go to the appropriate location and zoom level just fine but can't figure out how to trigger the marker's popup. I tried storing a reference while creating the popup but am not sure what function to open it with.

**Comment by bmeredyk** [comment]
I have this mostly figured out. Instead of placing the ref on the mgl-popup component put it on the mgl-marker. Since I'm creating a bunch of markers in a v-for loop the ref="markers" ends up being a list. Then when your user picks a location from the external list you need to figure out the appropriate index with in your markers ref list and once you have it you can get at the underlying mapbox marker's api.


```
//is the marker's popup already open?
this.$refs.markers[desiredMarkerIndex].marker._popup.isOpen()

//if it isn't, you can open it  (or if it is open, this will close it) using togglePopup()
this.$refs.markers[desiredMarkerIndex].togglePopup()

//if you need to close all other marker's popups (so only one is showing at a time)
_.forEach(this.$refs.markers, function(marker, index){
              if(index != desiredMarkerIndex){
                    marker.marker._popup.remove()
                }
          });
```

**Comment by soal** [comment]
Well, in short, you found (almost) the right way. Instead of using underlying Mapbox marker method, you can use `.togglePopup()` [method](https://soal.github.io/vue-mapbox/api/marker.html#methods) of MglMarker itself.
VueMapbox is follows Mabpox GL JS here. As you can see in the [docs](https://docs.mapbox.com/mapbox-gl-js/api/#marker) there is method to toggle popup on marker amd none on popup itself.
